//!GENERATED by tatara-rust-derive::PerFieldDeriveSpec.
//!Do not hand-edit; regenerate from the (defperfield …) source.
use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DataStruct, DeriveInput, Fields, parse_macro_input};
#[proc_macro_derive(InvalidatingSetter, attributes(invalidating_setter))]
pub fn derive_invalidating_setter(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let self_name = &input.ident;
    let fields = match &input.data {
        Data::Struct(DataStruct { fields: Fields::Named(named), .. }) => &named.named,
        _ => {
            return syn::Error::new_spanned(
                    self_name,
                    "PerFieldDerive requires a named-fields struct",
                )
                .to_compile_error()
                .into();
        }
    };
    const SKIP_FIELDS: &[&str] = &["last_seqno"];
    let per_field = fields
        .iter()
        .filter(|f| {
            f.ident
                .as_ref()
                .is_none_or(|id| !SKIP_FIELDS.contains(&id.to_string().as_str()))
        })
        .filter(|f| { f.attrs.iter().any(|a| a.path().is_ident("invalidating_setter")) })
        .map(|f| {
            let field_name = f.ident.as_ref().expect("named field has ident");
            let field_ty = &f.ty;
            let method_ident = quote::format_ident!("set_{}", field_name.to_string());
            quote! {
                pub fn # method_ident(& mut self, v : # field_ty) { self.# field_name =
                v; self.last_seqno = 0; }
            }
        });
    let expanded = quote! {
        impl # self_name { # (# per_field) * }
    };
    TokenStream::from(expanded)
}
